import NextAuth from 'next-auth'
import Nodemailer from 'next-auth/providers/nodemailer'
import type { Adapter } from 'next-auth/adapters'
import { DeleteCommand,GetCommand,PutCommand,QueryCommand } from '@aws-sdk/lib-dynamodb'
import { nanoid } from 'nanoid'
import { dynamo,tables } from '@/lib/aws'
const adapter:Adapter={
 async createUser(user){const item={...user,id:nanoid(),pk:`USER#${user.email}`,sk:'PROFILE'};await dynamo.send(new PutCommand({TableName:tables.auth,Item:item}));return item},
 async getUser(id){const r=await dynamo.send(new QueryCommand({TableName:tables.auth,IndexName:'byId',KeyConditionExpression:'#id=:id',ExpressionAttributeNames:{'#id':'id'},ExpressionAttributeValues:{':id':id},Limit:1}));return (r.Items?.[0] as never)||null},
 async getUserByEmail(email){const r=await dynamo.send(new GetCommand({TableName:tables.auth,Key:{pk:`USER#${email}`,sk:'PROFILE'}}));return (r.Item as never)||null},
 async getUserByAccount(){return null},async updateUser(user){const current=await this.getUser!(user.id);if(!current)throw new Error('User not found');const item={...current,...user};await dynamo.send(new PutCommand({TableName:tables.auth,Item:item}));return item as never},async deleteUser(){},async linkAccount(account){return account},async unlinkAccount(){},
 async createSession(session){await dynamo.send(new PutCommand({TableName:tables.auth,Item:{pk:`SESSION#${session.sessionToken}`,sk:'SESSION',...session,expiresAt:Math.floor(session.expires.getTime()/1000)}}));return session},async getSessionAndUser(token){const r=await dynamo.send(new GetCommand({TableName:tables.auth,Key:{pk:`SESSION#${token}`,sk:'SESSION'}}));if(!r.Item)return null;const user=await this.getUser!(r.Item.userId);return user?{session:{sessionToken:token,userId:r.Item.userId,expires:new Date(r.Item.expires)},user}:null},async updateSession(session){const existing=await this.getSessionAndUser!(session.sessionToken);if(!existing)return null;const merged={...existing.session,...session};await this.createSession!(merged);return merged},async deleteSession(token){await dynamo.send(new DeleteCommand({TableName:tables.auth,Key:{pk:`SESSION#${token}`,sk:'SESSION'}}))},
 async createVerificationToken(token){await dynamo.send(new PutCommand({TableName:tables.auth,Item:{pk:`TOKEN#${token.identifier}`,sk:token.token,...token,expiresAt:Math.floor(token.expires.getTime()/1000)}}));return token},async useVerificationToken({identifier,token}){const key={pk:`TOKEN#${identifier}`,sk:token};const r=await dynamo.send(new GetCommand({TableName:tables.auth,Key:key}));if(!r.Item)return null;await dynamo.send(new DeleteCommand({TableName:tables.auth,Key:key}));return {identifier:r.Item.identifier,token:r.Item.token,expires:new Date(r.Item.expires)}}
}
const authSecret=process.env.AUTH_SECRET || 'agentguard-default-secret-change-me'
export const {handlers,auth,signIn,signOut}=NextAuth({adapter,secret:authSecret,trustHost:true,providers:[Nodemailer({server:{host:'smtp.gmail.com',port:465,secure:true,auth:{user:process.env.AUTH_GMAIL_ID||process.env.GMAIL_USER,pass:process.env.AUTH_GMAIL_SECRET||process.env.GMAIL_APP_PASSWORD}},from:process.env.EMAIL_FROM||process.env.AUTH_GMAIL_ID})],pages:{signIn:'/signin'},session:{strategy:'database'}})
