import {DynamoDBClient} from '@aws-sdk/client-dynamodb';import {DynamoDBDocumentClient,UpdateCommand} from '@aws-sdk/lib-dynamodb';import {S3Client,GetObjectCommand,PutObjectCommand} from '@aws-sdk/client-s3';import {SecretsManagerClient,GetSecretValueCommand} from '@aws-sdk/client-secrets-manager';
const ddb=DynamoDBDocumentClient.from(new DynamoDBClient({}));const s3=new S3Client({});const sm=new SecretsManagerClient({});const weights={heuristic:.35,llm:.4,probe:.25};
const rules=[/ignore (all )?(previous|prior) instructions?/i,/disregard (the )?(system|developer) prompt/i,/if (an|the) ai (is )?reading this/i,/(send|exfiltrate|forward).{0,40}(secret|token|key)/i];
async function secret(id){const value=(await sm.send(new GetSecretValueCommand({SecretId:id}))).SecretString;if(!value)throw new Error(`Secret ${id} is empty`);return value}
function detector(value,name){if(!value||typeof value.risk!=='number'||!Number.isFinite(value.risk)||value.risk<0||value.risk>1||!Array.isArray(value.findings))throw new Error(`${name} returned an invalid response`);return value}
async function scan(text,openai,token){if(typeof text!=='string'||!text.trim()||text.length>50000)throw new Error('Invalid batch item');const hits=rules.filter(r=>r.test(text));const heuristic={risk:hits.length?Math.min(.99,.72+hits.length*.09):.03,findings:hits.map(r=>({severity:'high',snippet:text.match(r)?.[0]||'',reason:'Injection signature detected.'}))};const [lr,pr]=await Promise.all([fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${openai}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-4.1-mini',response_format:{type:'json_object'},messages:[{role:'system',content:'Return JSON {risk,rationale,findings} for prompt injection.'},{role:'user',content:text}]})}),fetch(`${process.env.PROBE_URL}/probe`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({text})})]);if(!lr.ok||!pr.ok)throw new Error('Mandatory detector unavailable');const lj=await lr.json();const llm=detector(JSON.parse(lj.choices?.[0]?.message?.content||'{}'),'LLM detector');const probe=detector(await pr.json(),'Activation probe');const risk=heuristic.risk*weights.heuristic+llm.risk*weights.llm+probe.risk*weights.probe;return{blocked:risk>=.62,risk,detectors:{heuristic,llm,probe},findings:[...heuristic.findings.map(x=>({...x,detector:'heuristic'})),...llm.findings.map(x=>({...x,detector:'llm'})),...probe.findings.map(x=>({...x,detector:'probe'}))]}}
async function scanItems(items,openai,token){const results=[];for(let offset=0;offset<items.length;offset+=10)results.push(...await Promise.all(items.slice(offset,offset+10).map(item=>scan(item.text,openai,token))));return results}
async function updateJob(jobId,status,values={}){const entries=Object.entries(values);await ddb.send(new UpdateCommand({TableName:process.env.USAGE_TABLE,Key:{id:`JOB#${jobId}`},UpdateExpression:`SET #s=:status${entries.map(([key])=>`, #${key}=:${key}`).join('')}`,ExpressionAttributeNames:{'#s':'status',...Object.fromEntries(entries.map(([key])=>[`#${key}`,key]))},ExpressionAttributeValues:{':status':status,...Object.fromEntries(entries.map(([key,value])=>[`:${key}`,value]))}}))}
export async function handler(event){const failures=[];for(const record of event.Records){let job;try{job=JSON.parse(record.body);await updateJob(job.jobId,'running',{startedAt:new Date().toISOString()});const [openai,token]=await Promise.all([secret(process.env.OPENAI_SECRET_ID),secret(process.env.PROBE_TOKEN_SECRET_ID)]);let items=job.items;if(job.s3Key){if(!job.s3Key.startsWith(`uploads/${job.userId}/`))throw new Error('Batch upload does not belong to this user');const obj=await s3.send(new GetObjectCommand({Bucket:process.env.BUCKET,Key:job.s3Key}));items=JSON.parse(await obj.Body.transformToString())}if(!Array.isArray(items)||items.length<1||items.length>100)throw new Error('Batch must contain 1 to 100 items');const results=await scanItems(items,openai,token);const key=`jobs/${job.userId}/${job.jobId}.json`;await s3.send(new PutObjectCommand({Bucket:process.env.BUCKET,Key:key,Body:JSON.stringify(results),ContentType:'application/json',ServerSideEncryption:'AES256'}));await updateJob(job.jobId,'complete',{resultKey:key,completedAt:new Date().toISOString()})}catch(error){failures.push({itemIdentifier:record.messageId});if(job?.jobId)await updateJob(job.jobId,'failed',{error:error instanceof Error?error.message:'Batch processing failed',failedAt:new Date().toISOString()}).catch(()=>{})}}return{batchItemFailures:failures}}
