import { redirect } from 'next/navigation'
import { QueryCommand } from '@aws-sdk/lib-dynamodb'
import { Activity,BarChart3,BookOpen,KeyRound,ScanSearch,Shield,ShieldCheck } from 'lucide-react'
import { auth,signOut } from '@/auth'
import { dynamo,tables } from '@/lib/aws'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table'
import Link from 'next/link'
export default async function Dashboard(){const session=await auth();if(!session?.user?.id)redirect('/signin');const scans=await dynamo.send(new QueryCommand({TableName:tables.scans,IndexName:'byOwner',KeyConditionExpression:'ownerId=:id',ExpressionAttributeValues:{':id':session.user.id},ScanIndexForward:false,Limit:20}));const rows=scans.Items||[];const blocked=rows.filter(x=>x.blocked).length;return <main className="min-h-screen bg-muted"><header className="border-b bg-background"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-6"><Link href="/" className="flex items-center gap-2 font-semibold"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Shield className="size-4"/></span>AgentGuard</Link><form action={async()=>{'use server';await signOut({redirectTo:'/'})}}><Button variant="outline" size="sm">Sign out</Button></form></div></header><div className="mx-auto grid max-w-7xl gap-5 px-4 py-8 md:px-6 lg:grid-cols-[220px_1fr]"><aside className="flex flex-col gap-1"><Button variant="secondary" className="justify-start"><BarChart3/>Overview</Button><Button render={<Link href="/app/keys"/>} nativeButton={false} variant="ghost" className="justify-start"><KeyRound/>API keys</Button><Button render={<Link href="/app/docs"/>} nativeButton={false} variant="ghost" className="justify-start"><BookOpen/>Docs</Button></aside><section className="flex min-w-0 flex-col gap-5"><div><h1 className="text-3xl font-semibold tracking-tight">Security overview</h1><p className="mt-1 text-muted-foreground">Live activity for {session.user.email}</p></div><div className="grid gap-4 sm:grid-cols-3"><Metric icon={ScanSearch} label="Recent scans" value={rows.length}/><Metric icon={ShieldCheck} label="Blocked" value={blocked}/><Metric icon={Activity} label="Block rate" value={`${rows.length?Math.round(blocked/rows.length*100):0}%`}/></div><Card><CardHeader><CardTitle>Scan history</CardTitle><CardDescription>Most recent API and dashboard requests.</CardDescription></CardHeader><CardContent>{rows.length?<Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Source</TableHead><TableHead>Risk</TableHead><TableHead>Verdict</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell>{new Date(r.createdAt).toLocaleString()}</TableCell><TableCell className="font-mono text-xs">{r.source}</TableCell><TableCell>{Math.round(r.risk*100)}</TableCell><TableCell><Badge variant={r.blocked?'destructive':'secondary'}>{r.blocked?'Blocked':'Allowed'}</Badge></TableCell></TableRow>)}</TableBody></Table>:<div className="flex min-h-52 flex-col items-center justify-center text-center"><ScanSearch className="size-8 text-muted-foreground"/><p className="mt-3 font-medium">No scans yet</p><p className="mt-1 text-sm text-muted-foreground">Create an API key or use the playground to begin.</p></div>}</CardContent></Card></section></div></main>}
function Metric({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:string|number}){return <Card><CardHeader className="pb-2"><div className="flex items-center justify-between"><CardDescription>{label}</CardDescription><Icon className="size-4 text-muted-foreground"/></div><CardTitle className="text-3xl tabular-nums">{value}</CardTitle></CardHeader></Card>}
