import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BarChart3,BookOpen,KeyRound } from 'lucide-react'
import { getSession } from '@/lib/auth'
import { getWorkspace } from '@/lib/workspace'
import { AgentGuardLogo } from '@/components/agentguard-logo'
import { PlatformConsole } from '@/components/platform-console'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
export default async function Dashboard(){const session=await getSession();if(!session?.user?.id)redirect('/login');const workspace=await getWorkspace(session.user);return <main className="min-h-screen"><header className="border-b"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/"><AgentGuardLogo/></Link><div className="flex items-center gap-2"><Badge variant="outline">{workspace.name} · {workspace.role}</Badge></div></div></header><section className="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-muted-foreground">Security console</p><h1 className="mt-4 text-4xl font-medium tracking-[-.04em] md:text-6xl">Control the boundary.</h1><p className="mt-4 max-w-2xl text-muted-foreground">Investigate scans, publish policy versions, route alerts, and manage access from your isolated workspace.</p></div><div className="flex flex-wrap gap-2"><Button render={<Link href="/app/benchmark"/>} nativeButton={false} variant="outline"><BarChart3/>Benchmark</Button><Button render={<Link href="/app/keys"/>} nativeButton={false} variant="outline"><KeyRound/>API keys</Button><Button render={<Link href="/app/docs"/>} nativeButton={false} variant="outline"><BookOpen/>Docs</Button></div></div><PlatformConsole/></section></main>}
