import Link from 'next/link'
import { ArrowLeft,ArrowRight } from 'lucide-react'
import { AgentGuardLogo } from '@/components/agentguard-logo'
import { Button } from '@/components/ui/button'
const samples=[['cURL',`curl -X POST "$BASE_URL/api/v1/scan" \\\n -H "Authorization: Bearer ag_live_..." \\\n -H "Content-Type: application/json" \\\n -d '{"text":"...","source":"WEB_PAGE"}'`],['TypeScript',`const result = await fetch('/api/v1/scan', {
  method: 'POST',
  headers: { Authorization: \`Bearer \${key}\` },
  body: JSON.stringify(input)
}).then(r => r.json())`],['Python',`result = requests.post(
  f"{base}/api/v1/scan",
  headers={"Authorization": f"Bearer {key}"},
  json=input
).json()`]]
export default async function Docs(){return <main className="min-h-screen"><header className="border-b"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><AgentGuardLogo/><Button render={<Link href='/app'/>} nativeButton={false} variant="ghost" size="sm"><ArrowLeft/>Back</Button></div></header><div className="mx-auto grid max-w-7xl lg:grid-cols-[240px_1fr]"><aside className="hidden min-h-[calc(100vh-4rem)] border-r p-6 lg:block"><p className="font-mono text-xs uppercase tracking-widest text-muted-foreground">API reference</p><nav className="mt-6 flex flex-col gap-3 text-sm"><a href="#quickstart" className="font-medium">Quickstart</a><a href="#examples" className="text-muted-foreground">Examples</a><a href="#model" className="text-muted-foreground">Risk model</a></nav></aside><article className="min-w-0 px-5 py-12 lg:px-12 lg:py-16"><section id="quickstart" className="border-b pb-12"><p className="font-mono text-xs uppercase tracking-[.2em] text-muted-foreground">Scan API</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-medium tracking-[-.05em] md:text-7xl">Three detectors. One stable contract.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Screen inbound content synchronously before adding it to model context. Every mandatory detector must respond.</p><Button render={<Link href="/app/keys"/>} nativeButton={false} className="mt-8 rounded-full">Create an API key<ArrowRight/></Button></section><section id="examples" className="py-12"><h2 className="text-3xl font-medium tracking-tight">Send a scan</h2><div className="mt-8 flex flex-col gap-10">{samples.map(([title,code])=><div key={title}><div className="mb-3 flex items-center justify-between"><h3 className="font-medium">{title}</h3><span className="font-mono text-xs text-muted-foreground">POST /api/v1/scan</span></div><pre className="overflow-x-auto border bg-primary p-5 font-mono text-sm leading-relaxed text-primary-foreground"><code>{code}</code></pre></div>)}</div></section><section id="model" className="border-t py-12"><h2 className="text-3xl font-medium tracking-tight">Risk model</h2><div className="mt-8 grid border md:grid-cols-3"><Model name="Heuristic" weight="35%"/><Model name="LLM judge" weight="40%"/><Model name="Activation probe" weight="25%"/></div><p className="mt-6 max-w-2xl leading-relaxed text-muted-foreground">Requests are blocked at risk ≥ 0.62. Supported sources include user prompts, trusted tools, tool output, web pages, documents, and MCP output.</p></section></article></div></main>}
function Model({name,weight}:{name:string;weight:string}){return <div className="border-b p-6 last:border-b-0 md:border-r md:border-b-0 md:last:border-r-0"><p className="text-sm text-muted-foreground">{name}</p><p className="mt-8 font-mono text-4xl">{weight}</p></div>}
