import Link from 'next/link'
import { ArrowDown, ArrowRight, BrainCircuit, Code2, Fingerprint, Network, ShieldAlert } from 'lucide-react'
import { AgentGuardMark } from '@/components/agentguard-logo'
import { Button } from '@/components/ui/button'
import { ScannerPlayground } from '@/components/scanner-playground'
import { SiteHeader } from '@/components/site-header'

export default function Page(){return <main><SiteHeader/>
 <section className="editorial-grid border-b"><div className="mx-auto flex min-h-[680px] max-w-7xl flex-col justify-between px-5 py-12 lg:px-8 lg:py-16"><div className="flex items-center gap-3 font-mono text-xs uppercase tracking-[.18em] text-muted-foreground"><span className="size-2 rounded-full bg-accent-foreground"/>Inbound security for autonomous systems</div><div className="py-20 lg:py-28"><h1 className="text-display max-w-6xl text-balance text-[clamp(4rem,10vw,9rem)] font-medium">Trust nothing your agent reads.</h1><div className="mt-10 flex flex-col justify-between gap-8 border-t pt-6 md:flex-row md:items-start"><p className="max-w-xl text-pretty text-lg leading-relaxed text-muted-foreground md:text-xl">AgentGuard inspects pages, documents, tool output, and MCP responses before untrusted text can steer your AI system.</p><div className="flex shrink-0 flex-wrap gap-3"><Button render={<a href="#scanner"/>} nativeButton={false} size="lg" className="rounded-full px-5">Test the scanner<ArrowDown/></Button><Button render={<Link href="/app/docs"/>} nativeButton={false} variant="outline" size="lg" className="rounded-full px-5">View API<ArrowRight/></Button></div></div></div></div></section>
 <section className="border-b bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl lg:grid-cols-4"><div className="flex min-h-72 flex-col justify-between border-b border-primary-foreground/20 p-6 lg:border-b-0 lg:border-r lg:p-8"><AgentGuardMark className="size-12"/><p className="max-w-xs text-2xl font-medium tracking-tight">A security boundary built for the age of agents.</p></div><Signal icon={Network} index="01" title="Deterministic" copy="Fast pattern and structure analysis catches known injection strategies."/><Signal icon={BrainCircuit} index="02" title="Semantic" copy="A model judge evaluates intent, deception, and instruction hierarchy."/><Signal icon={Fingerprint} index="03" title="Activation" copy="A local DeBERTa probe inspects internal representation anomalies."/></div></section>
 <ScannerPlayground/>
 <section id="approach" className="border-b"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-32"><p className="font-mono text-xs uppercase tracking-[.2em] text-muted-foreground">The operating principle</p><div className="mt-8 grid gap-12 lg:grid-cols-2"><h2 className="text-balance text-5xl font-medium tracking-[-.05em] md:text-7xl">Security before context.</h2><div className="flex flex-col gap-8 text-lg leading-relaxed text-muted-foreground"><p>Most agent defenses monitor what a model produces. AgentGuard protects what the model consumes—the untrusted text that can quietly reshape its goals.</p><p>Every detector is mandatory. If infrastructure is unavailable, the request is blocked rather than silently bypassed.</p><Link href="/app/docs" className="inline-flex w-fit items-center gap-2 border-b border-foreground pb-1 text-base font-medium text-foreground">Integrate AgentGuard<ArrowRight className="size-4"/></Link></div></div></div></section>
 <footer className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-16 px-5 py-12 lg:px-8"><div className="flex items-center gap-3"><AgentGuardMark/><span className="text-xl font-medium">AgentGuard</span></div><div className="flex flex-col justify-between gap-5 border-t border-primary-foreground/20 pt-5 text-sm text-primary-foreground/60 md:flex-row"><span>Inbound security for AI agents.</span><span>Heuristic · Semantic · Activation</span></div></div></footer>
 </main>}

function Signal({icon:Icon,index,title,copy}:{icon:typeof Code2;index:string;title:string;copy:string}){return <div className="flex min-h-72 flex-col justify-between border-b border-primary-foreground/20 p-6 last:border-b-0 lg:border-b-0 lg:border-r lg:last:border-r-0 lg:p-8"><div className="flex items-center justify-between"><Icon className="size-6"/><span className="font-mono text-xs text-primary-foreground/50">{index}</span></div><div><h3 className="text-2xl font-medium">{title}</h3><p className="mt-3 text-sm leading-relaxed text-primary-foreground/60">{copy}</p></div></div>}
