'use client'
import { useState } from 'react'
import useSWR from 'swr'
import { Copy,KeyRound,LoaderCircle,Plus,Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
const fetcher=(u:string)=>fetch(u).then(r=>r.json())
export function KeyManager(){const {data,mutate,isLoading}=useSWR('/api/keys',fetcher);const [name,setName]=useState('Production');const [created,setCreated]=useState('');async function create(){const r=await fetch('/api/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)return toast.error(d.error);setCreated(d.key);mutate()}return <div className="flex flex-col gap-10"><section><div className="mb-5"><h2 className="text-xl font-medium">Create a key</h2><p className="mt-1 text-sm text-muted-foreground">The secret is shown once. Store it in a secure vault.</p></div><div className="flex flex-col gap-3 border p-4 sm:flex-row"><Input value={name} onChange={e=>setName(e.target.value)} aria-label="Key name" className="h-11"/><Button onClick={create} size="lg" className="h-11 rounded-full px-5"><Plus/>Create key</Button></div></section>{created&&<section className="border border-accent-foreground/30 bg-accent/30 p-5"><h2 className="font-medium">Copy your new key</h2><p className="mt-1 text-sm text-muted-foreground">You won&apos;t be able to view it again.</p><div className="mt-4 flex items-center gap-2"><code className="min-w-0 flex-1 truncate border bg-background p-3 font-mono text-sm">{created}</code><Button variant="outline" onClick={()=>{navigator.clipboard.writeText(created);toast.success('Key copied')}}><Copy/>Copy</Button></div></section>}<section><h2 className="text-xl font-medium">Active keys</h2><div className="mt-5 border">{isLoading?<div className="flex h-28 items-center justify-center"><LoaderCircle className="animate-spin"/></div>:data?.length?data.map((k:{keyHash:string;name:string;prefix:string;createdAt:string})=><div key={k.keyHash} className="flex items-center gap-3 border-b p-4 last:border-b-0"><KeyRound className="size-4 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="font-medium">{k.name}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{k.prefix}…</p></div><Badge variant="secondary">Live</Badge><Button variant="ghost" size="icon" aria-label={`Revoke ${k.name}`} onClick={async()=>{await fetch(`/api/keys?keyHash=${k.keyHash}`,{method:'DELETE'});mutate()}}><Trash2/></Button></div>):<div className="flex h-28 items-center justify-center text-sm text-muted-foreground">No active keys.</div>}</div></section></div>}
