'use client'
import { useState } from 'react'
import useSWR from 'swr'
import { Copy,KeyRound,LoaderCircle,Plus,Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
const fetcher=(u:string)=>fetch(u).then(r=>r.json())
export function KeyManager(){const {data,mutate,isLoading}=useSWR('/api/keys',fetcher);const [name,setName]=useState('Production');const [created,setCreated]=useState('');async function create(){const r=await fetch('/api/keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)return toast.error(d.error);setCreated(d.key);mutate()}return <div className="flex flex-col gap-5"><Card><CardHeader><CardTitle>Create an API key</CardTitle><CardDescription>The secret is shown once. Store it in a secure vault.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row"><Input value={name} onChange={e=>setName(e.target.value)} aria-label="Key name"/><Button onClick={create}><Plus/>Create key</Button></CardContent></Card>{created&&<Card><CardHeader><CardTitle>Copy your new key</CardTitle><CardDescription>You won&apos;t be able to view it again.</CardDescription></CardHeader><CardContent className="flex items-center gap-2"><code className="min-w-0 flex-1 truncate rounded-lg bg-muted p-3 font-mono text-sm">{created}</code><Button variant="outline" onClick={()=>{navigator.clipboard.writeText(created);toast.success('Key copied')}}><Copy/>Copy</Button></CardContent></Card>}<Card><CardHeader><CardTitle>Active keys</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{isLoading?<LoaderCircle className="animate-spin"/>:data?.length?data.map((k:{keyHash:string;name:string;prefix:string;createdAt:string})=><div key={k.keyHash} className="flex items-center gap-3 rounded-lg border p-3"><KeyRound className="size-4 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="font-medium">{k.name}</p><p className="font-mono text-xs text-muted-foreground">{k.prefix}…</p></div><Badge variant="secondary">Live</Badge><Button variant="ghost" size="icon" aria-label={`Revoke ${k.name}`} onClick={async()=>{await fetch(`/api/keys?keyHash=${k.keyHash}`,{method:'DELETE'});mutate()}}><Trash2/></Button></div>):<p className="text-sm text-muted-foreground">No API keys. Create one to call the developer API.</p>}</CardContent></Card></div>}
