'use client'
import { useMemo,useState } from 'react'
import useSWR from 'swr'
import { Activity,AlertTriangle,BarChart3,Bell,Copy,FileSearch,KeyRound,Loader2,RefreshCw,Save,Send,ShieldCheck,Users } from 'lucide-react'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Progress } from '@/components/ui/progress'
import { Select,SelectContent,SelectGroup,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'

type Scan={id:string;createdAt:string;source:string;risk:number;blocked:boolean;latencyMs:number;findings?:{snippet:string;reason:string;detector:string}[];policy?:{name:string;version:number}}
type Policy={id:string;name:string;version:number;threshold:number;weights:{heuristic:number;llm:number;probe:number};allowPhrases:string[];blockPhrases:string[];failClosed:boolean;status:string}
type Member={id:string;email:string;role:string}
type Hook={id:string;url:string;events:string[];active:boolean;lastStatus?:number}
const fetcher=(url:string)=>fetch(url).then(async r=>{if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r.json()})
export function PlatformConsole(){const [tab,setTab]=useState('overview');const {data,error,isLoading,mutate}=useSWR('/api/platform',fetcher);const scans:Scan[]=data?.scans||[];const blocked=scans.filter(s=>s.blocked).length;const avg=Math.round(scans.reduce((n,s)=>n+(s.latencyMs||0),0)/(scans.length||1));const sources=useMemo(()=>Object.entries(scans.reduce<Record<string,number>>((a,s)=>(a[s.source]=(a[s.source]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]),[scans]);return <Tabs value={tab} onValueChange={setTab} className="mt-8"><TabsList className="h-auto w-full justify-start overflow-x-auto rounded-none border-b bg-transparent p-0"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="scans">Scans</TabsTrigger><TabsTrigger value="policies">Policies</TabsTrigger><TabsTrigger value="alerts">Alerts</TabsTrigger><TabsTrigger value="team">Team</TabsTrigger></TabsList>{error&&<p className="mt-6 text-sm text-destructive">{error.message}</p>}{isLoading?<Loader2 className="mt-10 animate-spin"/>:<><TabsContent value="overview"><div className="grid border-b sm:grid-cols-3"><Metric icon={FileSearch} label="Requests" value={scans.length}/><Metric icon={ShieldCheck} label="Blocked" value={blocked}/><Metric icon={Activity} label="Avg latency" value={`${avg}ms`}/></div><div className="grid gap-8 py-10 lg:grid-cols-2"><Card><CardHeader><CardTitle>Risk distribution</CardTitle><CardDescription>Recent request severity across the active workspace.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5">{[['Critical',scans.filter(s=>s.risk>=.8).length],['Elevated',scans.filter(s=>s.risk>=.5&&s.risk<.8).length],['Low',scans.filter(s=>s.risk<.5).length]].map(([name,count])=><div key={name as string}><div className="mb-2 flex justify-between text-sm"><span>{name}</span><span className="font-mono">{count}</span></div><Progress value={Number(count)/(scans.length||1)*100}/></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Sources</CardTitle><CardDescription>Where untrusted input is entering your agents.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{sources.length?sources.map(([source,count])=><div className="flex items-center justify-between border-b pb-3" key={source}><span className="font-mono text-xs">{source}</span><Badge variant="secondary">{count}</Badge></div>):<p className="text-sm text-muted-foreground">No source data yet.</p>}</CardContent></Card></div></TabsContent><TabsContent value="scans"><ScanHistory scans={scans} mutate={mutate}/></TabsContent><TabsContent value="policies"><PolicyEditor policy={data?.policy} mutate={mutate}/></TabsContent><TabsContent value="alerts"><WebhookManager hooks={data?.webhooks||[]} mutate={mutate}/></TabsContent><TabsContent value="team"><TeamManager members={data?.members||[]} role={data?.workspace?.role} mutate={mutate}/></TabsContent></>}</Tabs>}
function Metric({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:string|number}){return <div className="border-b p-6 last:border-b-0 sm:border-r sm:border-b-0 sm:last:border-r-0"><div className="flex items-center justify-between text-sm text-muted-foreground"><span>{label}</span><Icon/></div><p className="mt-8 font-mono text-4xl tracking-tight">{value}</p></div>}
function ScanHistory({scans,mutate}:{scans:Scan[];mutate:()=>void}){const [selected,setSelected]=useState<Scan|null>(null);async function replay(id:string){const r=await fetch(`/api/platform/scans/${id}/replay`,{method:'POST'});const out=await r.json();if(!r.ok)return toast.error(out.error);toast.success(`Replay ${out.blocked?'blocked':'allowed'} at ${Math.round(out.risk*100)}% risk`);mutate()}return <div className="grid gap-8 py-8 lg:grid-cols-[1fr_340px]"><div className="overflow-hidden border"><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Source</TableHead><TableHead>Risk</TableHead><TableHead>Verdict</TableHead></TableRow></TableHeader><TableBody>{scans.map(scan=><TableRow key={scan.id} onClick={()=>setSelected(scan)} className="cursor-pointer"><TableCell className="font-mono text-xs">{new Date(scan.createdAt).toLocaleString()}</TableCell><TableCell>{scan.source}</TableCell><TableCell>{Math.round(scan.risk*100)}%</TableCell><TableCell><Badge variant={scan.blocked?'destructive':'secondary'}>{scan.blocked?'Blocked':'Allowed'}</Badge></TableCell></TableRow>)}</TableBody></Table></div><Card><CardHeader><CardTitle>{selected?'Scan evidence':'Select a scan'}</CardTitle><CardDescription>{selected?`${selected.source} · ${selected.policy?.name||'Default policy'}`:'Inspect detector evidence and replay decisions.'}</CardDescription></CardHeader><CardContent>{selected?<div className="flex flex-col gap-5"><div className="text-5xl font-medium">{Math.round(selected.risk*100)}%</div>{selected.findings?.map((f,i)=><div className="border-t pt-4" key={i}><p className="font-mono text-xs uppercase text-muted-foreground">{f.detector}</p><p className="mt-2 text-sm">{f.reason}</p><code className="mt-2 block text-xs text-muted-foreground">{f.snippet}</code></div>)}<Button onClick={()=>replay(selected.id)}><RefreshCw/>Replay current policy</Button></div>:null}</CardContent></Card></div>}
function PolicyEditor({policy,mutate}:{policy?:Policy;mutate:()=>void}){const [threshold,setThreshold]=useState(policy?.threshold??.62);const [block,setBlock]=useState((policy?.blockPhrases||[]).join('\n'));const [allow,setAllow]=useState((policy?.allowPhrases||[]).join('\n'));async function save(){const r=await fetch('/api/platform/policies',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Agent boundary',threshold,blockPhrases:block.split('\n').filter(Boolean),allowPhrases:allow.split('\n').filter(Boolean),failClosed:true})});if(!r.ok)return toast.error((await r.json()).error);toast.success('Policy version published');mutate()}return <div className="grid gap-8 py-8 lg:grid-cols-2"><Card><CardHeader><CardTitle>Decision threshold</CardTitle><CardDescription>Publish immutable policy versions. Fail-closed remains enforced.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><Label htmlFor="threshold">Block at risk score</Label><Input id="threshold" type="number" min="0" max="1" step="0.01" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="block">Blocked phrases</Label><Textarea id="block" className="mt-2 min-h-36" value={block} onChange={e=>setBlock(e.target.value)}/></div><div><Label htmlFor="allow">Allowed phrases</Label><Textarea id="allow" className="mt-2 min-h-36" value={allow} onChange={e=>setAllow(e.target.value)}/></div></div><Button onClick={save}><Save/>Publish policy</Button></CardContent></Card><Card><CardHeader><CardTitle>Detector weights</CardTitle><CardDescription>Weighted ensemble used for every decision.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{Object.entries(policy?.weights||{heuristic:.35,llm:.4,probe:.25}).map(([name,value])=><div key={name}><div className="mb-2 flex justify-between text-sm"><span className="capitalize">{name}</span><span>{Math.round(value*100)}%</span></div><Progress value={value*100}/></div>)}</CardContent></Card></div>}
function WebhookManager({hooks,mutate}:{hooks:Hook[];mutate:()=>void}){const [url,setUrl]=useState('');async function create(){const r=await fetch('/api/platform/webhooks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,events:['scan.blocked','risk.elevated','detector.degraded']})});const out=await r.json();if(!r.ok)return toast.error(out.error);toast.success('Webhook created — copy the signing secret now');await navigator.clipboard.writeText(out.secret);setUrl('');mutate()}return <div className="grid gap-8 py-8 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Alert destinations</CardTitle><CardDescription>Signed JSON delivery with bounded retries and delivery telemetry.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{hooks.map(h=><div className="flex items-center justify-between border-b pb-4" key={h.id}><div><p className="font-mono text-sm">{h.url}</p><p className="mt-1 text-xs text-muted-foreground">{h.events.join(' · ')}</p></div><Badge variant={h.active?'secondary':'outline'}>{h.active?'Active':'Paused'}</Badge></div>)}{!hooks.length&&<p className="text-sm text-muted-foreground">No webhook destinations configured.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Add destination</CardTitle><CardDescription>Supports HTTPS webhook and Slack workflow URLs.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Input type="url" placeholder="https://hooks.example.com/agentguard" value={url} onChange={e=>setUrl(e.target.value)}/><Button onClick={create} disabled={!url}><Bell/>Create webhook</Button></CardContent></Card></div>}
function TeamManager({members,role,mutate}:{members:Member[];role:string;mutate:()=>void}){const [email,setEmail]=useState('');const [inviteRole,setInviteRole]=useState('developer');async function invite(){const r=await fetch('/api/platform/team',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,role:inviteRole})});const out=await r.json();if(!r.ok)return toast.error(out.error);toast.success('Invitation created');setEmail('');mutate()}return <div className="grid gap-8 py-8 lg:grid-cols-[1fr_340px]"><Card><CardHeader><CardTitle>Workspace members</CardTitle><CardDescription>Role-scoped access to scans, policies, alerts, and keys.</CardDescription></CardHeader><CardContent>{members.map(m=><div className="flex items-center justify-between border-b py-4" key={m.id}><div><p>{m.email}</p><p className="text-xs text-muted-foreground">{m.id}</p></div><Badge variant="outline">{m.role}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Invite teammate</CardTitle><CardDescription>Only the invited email can accept.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Input type="email" placeholder="security@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><Select value={inviteRole} onValueChange={v=>v&&setInviteRole(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectGroup><SelectItem value="admin">Admin</SelectItem><SelectItem value="developer">Developer</SelectItem><SelectItem value="viewer">Viewer</SelectItem></SelectGroup></SelectContent></Select><Button onClick={invite} disabled={!email||!['owner','admin'].includes(role)}><Send/>Send invite</Button></CardContent></Card></div>}
